# -*- coding: utf-8 -*-
"""Référentiel des divisions administratives de l'Algérie (58 wilayas + communes).

Donnée de référence statique — aucune logique métier. Sert à peupler les menus
« Wilaya » / « Commune » de l'onglet Recherche à partir de la liste officielle,
et non plus à partir des valeurs libres trouvées en base.

L'Algérie compte officiellement **58 wilayas** depuis 2019 (les 48 historiques +
10 nouvelles wilayas promues des anciennes « wilayas déléguées » : Timimoun,
Bordj Badji Mokhtar, Ouled Djellal, Béni Abbès, In Salah, In Guezzam, Touggourt,
Djanet, El M'Ghair, El Meniaa).

Orthographe : translittération française usuelle et cohérente.

API exposée (ne pas renommer, du code en dépend) :
- ``WILAYAS``            : list[str]  — les 58 wilayas, ordre du code officiel (01→58).
- ``WILAYA_CODES``      : dict[str, str] — code officiel (2 chiffres) par nom de wilaya.
- ``COMMUNES_BY_WILAYA``: dict[str, list[str]] — communes par wilaya (clé = nom de wilaya).
"""

# Source : (code officiel, nom de la wilaya, [communes triées]).
_ALGERIA: list[tuple[str, str, list[str]]] = [
    ("01", "Adrar", [
        "Adrar", "Tamest", "Reggane", "In Zghmir", "Tit", "Ksar Kaddour",
        "Tsabit", "Sebaa", "Fenoughil", "Tamentit", "Zaouiet Kounta",
        "Bouda", "Aoulef", "Tamekten", "Tamantit", "Akabli", "Timokten",
        "Sali", "Tit",
    ]),
    ("02", "Chlef", [
        "Chlef", "Ténès", "Benairia", "El Karimia", "Tadjena", "Taougrite",
        "Beni Haoua", "Sobha", "Harchoun", "Ouled Fares", "Sidi Akkacha",
        "Boukadir", "Beni Rached", "Talassa", "Herenfa", "Oued Goussine",
        "Dahra", "Ouled Abbes", "Sendjas", "Zeboudja", "Oued Sly",
        "Abou El Hassane", "El Marsa", "Chettia", "Sidi Abderrahmane",
        "Moussadek", "El Hadjadj", "Labiod Medjadja", "Oued Fodda",
        "Ouled Ben Abdelkader", "Bouzeghaia", "Ain Merane", "Oum Drou",
        "Breira", "Beni Bouattab",
    ]),
    ("03", "Laghouat", [
        "Laghouat", "Ksar El Hirane", "Benacer Ben Chohra", "Sidi Makhlouf",
        "Hassi Delaa", "Hassi R'Mel", "Ain Madhi", "Tadjmout", "Kheneg",
        "Gueltat Sidi Saad", "Ain Sidi Ali", "Beidha", "Brida",
        "El Ghicha", "Hadj Mechri", "Sebgag", "Taouiala", "El Assafia",
        "Oued Morra", "Oued M'Zi", "El Haouaita", "Sidi Bouzid", "El Houaita",
        "Aflou",
    ]),
    ("04", "Oum El Bouaghi", [
        "Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Behir Chergui",
        "El Amiria", "Sigus", "El Belala", "Ain Babouche", "Berriche",
        "Ouled Hamla", "Dhala", "Ain Kercha", "Hanchir Toumghani",
        "El Djazia", "Ain Diss", "Fkirina", "Souk Naamane", "Zorg",
        "El Fedjoudj Boughrara Saoudi", "Ouled Zouai", "Bir Chouhada",
        "Ksar Sbahi", "Oued Nini", "Meskiana", "Ain Fakroun", "Rahia",
        "Ain Zitoun", "Ouled Gacem", "El Harmilia",
    ]),
    ("05", "Batna", [
        "Batna", "Ghassira", "Maafa", "Merouana", "Seriana", "Menaa",
        "El Madher", "Tazoult", "N'Gaous", "Guigba", "Inoughissen",
        "Ouyoun El Assafir", "Djerma", "Bitam", "Metkaouak", "Arris",
        "Kimmel", "Tilatou", "Ain Djasser", "Ouled Sellam", "Tigharghar",
        "Ain Yagout", "Fesdis", "Sefiane", "Rahbat", "Tighanimine",
        "Lemsane", "Ksar Bellezma", "Seggana", "Ichmoul", "Foum Toub",
        "Beni Foudhala El Hakania", "Oued El Ma", "Talkhamt", "Bouzina",
        "Chemora", "Oued Chaaba", "Taxlent", "Gosbat", "Ouled Aouf",
        "Boumagueur", "Barika", "Djezzar", "T'Kout", "Ain Touta",
        "Hidoussa", "Teniet El Abed", "Oued Taga", "Ouled Fadel",
        "Timgad", "Ras El Aioun", "Chir", "Ouled Si Slimane", "Zanet El Beida",
        "M'Doukal", "Ouled Ammar", "El Hassi", "Lazrou", "Boumia",
        "Boulhilat", "Larbaa",
    ]),
    ("06", "Béjaïa", [
        "Béjaïa", "Amizour", "Ferraoun", "Taourirt Ighil", "Chelata",
        "Tamokra", "Timezrit", "Souk El Tenine", "M'Cisna", "Tinebdar",
        "Tichy", "Semaoun", "Kendira", "Tifra", "Ighram", "Amalou",
        "Ighil Ali", "Fenaia Ilmaten", "Toudja", "Darguina", "Sidi Ayad",
        "Aokas", "Beni Djellil", "Adekar", "Akbou", "Seddouk",
        "Tazmalt", "Ait R'Zine", "Chemini", "Souk Oufella", "Taskriout",
        "Tibane", "Tala Hamza", "Barbacha", "Beni Ksila", "Ouzellaguen",
        "Bouhamza", "Beni Mellikeche", "Sidi Aich", "El Kseur",
        "Melbou", "Akfadou", "Leflaye", "Kherrata", "Draa El Caid",
        "Tamridjet", "Ait Smail", "Boukhelifa", "Tizi N'Berber",
        "Beni Maouche", "Oued Ghir", "Boudjellil",
    ]),
    ("07", "Biskra", [
        "Biskra", "Sidi Okba", "Chetma", "Ourlal", "Tolga", "Lioua",
        "Lichana", "Ouled Djellal", "Ras El Miaad", "Besbes", "Sidi Khaled",
        "Doucen", "Ech Chaiba", "Foughala", "Bordj Ben Azzouz", "Meziraa",
        "Bouchagroun", "M'Chouneche", "El Haouch", "Ain Naga", "Zeribet El Oued",
        "El Feidh", "El Kantara", "Ain Zaatout", "El Outaya", "Djemorah",
        "Branis", "El Ghrous", "Mekhadma", "El Hadjeb", "Khenguet Sidi Nadji",
        "M'Lili", "Oumache", "El Mizaraa",
    ]),
    ("08", "Béchar", [
        "Béchar", "Erg Ferradj", "Ouled Khoudir", "Meridja", "Timoudi",
        "Lahmar", "Beni Abbes", "Tabelbala", "Igli", "Taghit", "El Ouata",
        "Boukais", "Mogheul", "Abadla", "Kerzaz", "Ksabi", "Tamtert",
        "Beni Ikhlef", "Mechraa Houari Boumediene", "Kenadsa",
    ]),
    ("09", "Blida", [
        "Blida", "Chebli", "Bouinan", "Oued El Alleug", "Ouled Yaich",
        "Chrea", "El Affroun", "Chiffa", "Hammam Melouane", "Ben Khelil",
        "Soumaa", "Mouzaia", "Souhane", "Meftah", "Ouled Slama",
        "Bougara", "Guerouaou", "Ain Romana", "Djebabra", "Beni Tamou",
        "Bouarfa", "Beni Mered", "Boufarik", "Larbaa", "Oued Djer",
        "Beni Merad",
    ]),
    ("10", "Bouira", [
        "Bouira", "El Asnam", "Guerrouma", "Souk El Khemis", "Kadiria",
        "Hanif", "Dirah", "Ait Laaziz", "Taghzout", "Raouraoua", "Mezdour",
        "Haizer", "Lakhdaria", "Maala", "El Hachimia", "Aomar",
        "Chorfa", "Bordj Okhriss", "El Adjiba", "El Hakimia", "El Khabouzia",
        "Ahl El Ksar", "Bouderbala", "Zbarbar", "Ain El Hadjar",
        "Djebahia", "Aghbalou", "Taguedit", "Ain Turk", "Saharidj",
        "Dechmia", "Ridane", "Bechloul", "Boukram", "Ain Bessem",
        "Bir Ghbalou", "Mchedallah", "Sour El Ghozlane", "Maamora",
        "Ouled Rached", "Ain Laloui", "Hadjera Zerga", "Ath Mansour",
        "El Mokrani", "Oued El Berdi",
    ]),
    ("11", "Tamanrasset", [
        "Tamanrasset", "Abalessa", "In Ghar", "In Salah", "Idles",
        "Tazrouk", "In Amguel", "Foggaret Ezzoua",
    ]),
    ("12", "Tébessa", [
        "Tébessa", "Bir El Ater", "Cheria", "Stah Guentis", "El Aouinet",
        "Lahouidjbet", "Safsaf El Ouesra", "Hammamet", "Negrine",
        "Bir Mokkadem", "El Kouif", "Morsott", "El Ogla", "Bir Dheheb",
        "El Ogla El Malha", "Gorriguer", "Bekkaria", "Boukhadra",
        "Ouenza", "El Ma Labiodh", "Oum Ali", "Tlidjene", "Ain Zerga",
        "El Meridj", "Boulhaf Dyr", "Bedjene", "El Mazeraa", "Ferkane",
    ]),
    ("13", "Tlemcen", [
        "Tlemcen", "Beni Mester", "Ain Tallout", "Remchi", "El Fehoul",
        "Sabra", "Ghazaouet", "Souani", "Djebala", "El Gor", "Oued Chouly",
        "Ain Fezza", "Ouled Mimoun", "Amieur", "Ain Youcef", "Zenata",
        "Beni Snous", "Bab El Assa", "Dar Yaghmouracene", "Fellaoucene",
        "Azails", "Sebaa Chioukh", "Terni Beni Hediel", "Bensekrane",
        "Ain Nehala", "Hennaya", "Maghnia", "Hammam Boughrara", "Souahlia",
        "Msirda Fouaga", "Ain Fetah", "El Aricha", "Souk Tleta",
        "Sidi Abdelli", "Sebdou", "Beni Ouarsous", "Sidi Medjahed",
        "Beni Boussaid", "Marsa Ben M'Hidi", "Nedroma", "Sidi Djillali",
        "Beni Bahdel", "El Bouihi", "Honaine", "Tianet", "Ouled Riyah",
        "Bouhlou", "Souk El Khemis", "El Menzel", "Beni Semiel", "Ain Ghoraba",
        "Chetouane", "Mansourah", "Beni Khellad",
    ]),
    ("14", "Tiaret", [
        "Tiaret", "Medroussa", "Ain Bouchekif", "Sidi Ali Mellal",
        "Ain Zarit", "Ain Deheb", "Sidi Bakhti", "Medrissa", "Zmalet El Emir Abdelkader",
        "Madna", "Sebt", "Mellakou", "Dahmouni", "Rahouia", "Mahdia",
        "Sougueur", "Si Abdelghani", "Ain El Hadid", "Ouled Djerad",
        "Naima", "Meghila", "Guertoufa", "Sidi Hosni", "Djillali Ben Amar",
        "Sebaine", "Tousnina", "Frenda", "Ain Kermes", "Ksar Chellala",
        "Rechaiga", "Nadorah", "Tagdemt", "Oued Lilli", "Mechraa Safa",
        "Hamadia", "Chehaima", "Takhemaret", "Sidi Abderrahmane",
        "Serghine", "Bougara", "Faidja", "Tidda",
    ]),
    ("15", "Tizi Ouzou", [
        "Tizi Ouzou", "Ain El Hammam", "Akbil", "Freha", "Souamaa",
        "Mechtras", "Irdjen", "Timizart", "Makouda", "Draa El Mizan",
        "Tizi Gheniff", "Bounouh", "Ait Chafaa", "Frikat", "Beni Aissi",
        "Beni Zmenzer", "Iferhounene", "Azazga", "Iloula Oumalou",
        "Yakouren", "Larbaa Nath Irathen", "Tizi Rached", "Zekri",
        "Ouaguenoun", "Ain Zaouia", "M'Kira", "Ait Yahia", "Ait Mahmoud",
        "Maatka", "Ait Boumahdi", "Abi Youcef", "Beni Douala", "Illilten",
        "Bouzeguene", "Ait Aggouacha", "Ouadhias", "Azeffoun", "Tigzirt",
        "Ait Aissa Mimoun", "Boghni", "Ifigha", "Ait Oumalou", "Tirmitine",
        "Akerrou", "Yatafene", "Beni Ziki", "Draa Ben Khedda", "Ouacif",
        "Idjeur", "Mekla", "Tizi N'Tleta", "Beni Yenni", "Aghribs",
        "Iflissen", "Boudjima", "Ait Yahia Moussa", "Souk El Thenine",
        "Ait Khelil", "Sidi Naamane", "Iboudraren", "Agouni Gueghrane",
        "Mizrana", "Imsouhal", "Tadmait", "Ait Bouaddou", "Assi Youcef",
        "Ait Toudert",
    ]),
    ("16", "Alger", [
        "Alger Centre", "Sidi M'Hamed", "El Madania", "Hamma El Annasser",
        "Bab El Oued", "Bologhine Ibnou Ziri", "Casbah", "Oued Koriche",
        "Bir Mourad Rais", "El Biar", "Bouzareah", "Birkhadem",
        "El Harrach", "Baraki", "Oued Smar", "Bourouba", "Hussein Dey",
        "Kouba", "Bachedjerah", "Dar El Beida", "Bab Ezzouar", "Ben Aknoun",
        "Dely Ibrahim", "Bains Romains", "Rais Hamidou", "Djasr Kasentina",
        "El Mouradia", "Hydra", "Mohammadia", "Bordj El Kiffan",
        "El Magharia", "Beni Messous", "Les Eucalyptus", "Birtouta",
        "Tessala El Merdja", "Ouled Chebel", "Sidi Moussa", "Ain Taya",
        "Bordj El Bahri", "El Marsa", "H'Raoua", "Rouiba", "Reghaia",
        "Ain Benian", "Staoueli", "Zeralda", "Mahelma", "Rahmania",
        "Souidania", "Cheraga", "Ouled Fayet", "El Achour", "Draria",
        "Douera", "Baba Hassen", "Khraicia", "Saoula",
    ]),
    ("17", "Djelfa", [
        "Djelfa", "Moudjebara", "El Guedid", "Hassi Bahbah", "Ain Maabed",
        "Sed Rahal", "Feidh El Botma", "Birine", "Bouira Lahdab",
        "Zaccar", "El Khemis", "Sidi Baizid", "Mliliha", "El Idrissia",
        "Douis", "Hassi El Euch", "Messaad", "Guettara", "Sidi Ladjel",
        "Had Sahary", "Guernini", "Selmana", "Ain Chouhada", "Oum Laadham",
        "Dar Chioukh", "Charef", "Beni Yagoub", "Zaafrane", "Deldoul",
        "Ain El Ibel", "Ain Oussera", "Benhar", "Hassi Fedoul", "Amourah",
        "Ain Feka", "Tadmit",
    ]),
    ("18", "Jijel", [
        "Jijel", "Eraguene", "El Aouana", "Ziama Mansouriah", "Taher",
        "Emir Abdelkader", "Chekfa", "Chahna", "El Milia", "Sidi Maarouf",
        "Settara", "El Ancer", "Sidi Abdelaziz", "Kaous", "Ghebala",
        "Bouraoui Belhadef", "Djimla", "Selma Benziada", "Boudria Beni Yadjis",
        "Kheiri Oued Adjoul", "Texenna", "Djemaa Beni Habibi",
        "Bordj Tahar", "Ouled Yahia Khedrouche", "Ouled Rabah",
        "Boucif Ouled Askeur", "Khiri Oued Adjoul", "Ain Kechra",
    ]),
    ("19", "Sétif", [
        "Sétif", "Ain El Kebira", "Beni Aziz", "Ouled Sidi Ahmed",
        "Boutaleb", "Ain Roua", "Draa Kebila", "Bir Haddada", "Ouled Tebben",
        "Hamma", "Maaouia", "Ain Legradj", "Ain Abessa", "Dehamcha",
        "Babor", "Guidjel", "Ain Lahdjar", "Bousselam", "El Eulma",
        "Djemila", "Beni Ouartilane", "Rosfa", "Ouled Addouane",
        "Belaa", "Ain Arnat", "Amoucha", "Ain Oulmene", "Beni Fouda",
        "Tachouda", "Beidha Bordj", "Bouandas", "Bazer Sakhra",
        "Hammam Essokhna", "Mezloug", "Bir El Arch", "Beni Chebana",
        "Ouled Sabor", "Guenzet", "Talaifacene", "Bougaa", "Beni Mouhli",
        "Ouricia", "Tizi N'Bechar", "Salah Bey", "Ain Azel", "Guellal",
        "Ain Sebt", "Hammam Guergour", "Harbil", "El Ouldja", "Tella",
        "Maoklane", "Ait Naoual Mezada", "Ksar El Abtal", "Ait Tizi",
        "Serdj El Ghoul", "Tizi N'Bechar", "El Ouricia", "Oued El Bared",
        "Beni Hocine",
    ]),
    ("20", "Saïda", [
        "Saïda", "Doui Thabet", "Ain El Hadjar", "Ouled Khaled",
        "Moulay Larbi", "Youb", "Hounet", "Sidi Amar", "Sidi Boubekeur",
        "El Hassasna", "Maamora", "Sidi Ahmed", "Ain Sekhouna",
        "Ouled Brahim", "Tircine", "Ain Soltane",
    ]),
    ("21", "Skikda", [
        "Skikda", "Ain Zouit", "El Hadaiek", "Filfila", "Hamadi Krouma",
        "El Marsa", "Kerkera", "Ouled Attia", "Oum Toub", "Bekkouche Lakhdar",
        "Cheraia", "Zitouna", "Es Sebt", "Collo", "Beni Zid",
        "Kanoua", "Beni Oulbane", "Ain Kechra", "Oued Zhour", "Zerdazas",
        "Ouldja Boulbalout", "Kheneg Mayoum", "Bouchtata", "Salah Bouchaour",
        "Sidi Mezghiche", "Emjez Edchich", "Beni Bechir", "Ouled Hebaba",
        "Sidi Mezghiche", "El Ghedir", "Bin El Ouiden", "Ramdane Djamel",
        "Beni Bachir", "Azzaba", "Djendel Saadi Mohamed", "Ain Bouziane",
        "El Harrouch", "Zerdazas", "Ouled Zouai", "Tamalous", "Ain Cherchar",
        "Bouchtata", "Sidi Ali Boussidi", "El Bouni",
    ]),
    ("22", "Sidi Bel Abbès", [
        "Sidi Bel Abbès", "Tessala", "Sidi Brahim", "Mostefa Ben Brahim",
        "Telagh", "Mezaourou", "Boukhanafis", "Sidi Ali Boussidi",
        "Badredine El Mokrani", "Marhoum", "Tafissour", "Amarnas",
        "Tilmouni", "Sidi Lahcene", "Ain Thrid", "Makedra", "Tenira",
        "Moulay Slissen", "El Hacaiba", "Ain Tindamine", "Ain Kada",
        "Mcid", "Sidi Khaled", "Ain El Berd", "Sfisef", "Ain Adden",
        "Boudjebaa El Bordj", "Sidi Yacoub", "Sidi Hamadouche",
        "Belarbi", "Oued Taourira", "Dhaya", "Zerouala", "Lamtar",
        "Sidi Chaib", "Sidi Dahou Zairs", "Oued Sbaa", "Boudjebaa",
        "Hassi Zehana", "Tabia", "Merine", "Ras El Ma", "Chetouane Belaila",
        "Bir El Hammam", "Taoudmout", "Redjem Demouche", "Benachiba Chelia",
        "Hassi Dahou", "Teghalimet", "Ben Badis", "Sidi Ali Benyoub",
        "Chetouane", "Bir El Hammam",
    ]),
    ("23", "Annaba", [
        "Annaba", "Berrahal", "El Hadjar", "Eulma", "El Bouni",
        "Oued El Aneb", "Cheurfa", "Seraidi", "Ain Berda", "Chetaibi",
        "Sidi Amar", "Treat",
    ]),
    ("24", "Guelma", [
        "Guelma", "Nechmaya", "Bouati Mahmoud", "Oued Zenati", "Tamlouka",
        "Oued Fragha", "Ain Sandel", "Ras El Agba", "Dahouara", "Belkheir",
        "Ben Djerrah", "Bou Hamdane", "Ain Makhlouf", "Ain Ben Beida",
        "Khezara", "Beni Mezline", "Bou Hachana", "Guelaat Bou Sbaa",
        "Hammam N'Bail", "Ain Larbi", "Medjez Amar", "Bordj Sabath",
        "Hamman Debagh", "Roknia", "Nechmaya", "Oued Cheham", "Djeballah Khemissi",
        "El Fedjoudj", "Boumahra Ahmed", "Ain Reggada", "Heliopolis",
        "Ain Hessainia", "Sellaoua Announa", "Medjez Sfa",
    ]),
    ("25", "Constantine", [
        "Constantine", "Hamma Bouziane", "Ibn Ziad", "Zighoud Youcef",
        "Didouche Mourad", "El Khroub", "Ain Abid", "Beni Hamiden",
        "Ouled Rahmoune", "Ain Smara", "Messaoud Boudjeriou", "Ibn Badis",
    ]),
    ("26", "Médéa", [
        "Médéa", "Ouzera", "Ouled Maaref", "Ain Boucif", "Aziz",
        "Ouled Deide", "El Omaria", "Derrag", "El Guelbelkebir",
        "Bouaiche", "Mezerana", "Ouled Brahim", "Damiat", "Sidi Naamane",
        "Ouled Bouachra", "Sidi Zahar", "Oued Harbil", "Benchicao",
        "Sidi Damed", "Aissaouia", "Ouled Antar", "Draa Essamar",
        "Tafraout", "Bir Ben Laabed", "El Ouinet", "Ouled Hellal",
        "Tamesguida", "Ain Ouksir", "Oum El Djalil", "Ouamri", "Si Mahdjoub",
        "Zoubiria", "Ksar El Boukhari", "El Azizia", "Djouab", "Chahbounia",
        "Meftaha", "Mihoub", "Boughezoul", "Tablat", "Deux Bassins",
        "Beni Slimane", "Berrouaghia", "Souagui", "Rebaia", "Bouskene",
        "Mefatha", "Chelalet El Adhaoura", "Seghouane", "Meghraoua",
        "Cheniguel", "Ain Ouksir", "Ouled Bouachra", "Baata", "Boghar",
        "Sidi Errabia", "Bir Ben Abed", "El Hamdania", "Kef Lakhdar",
        "Draa Essamar", "Tletat Ed Douair", "Hannacha", "Sebt Aziz",
        "Ouled Emhamed", "Medjebar", "Khams Djouamaa", "Saneg",
    ]),
    ("27", "Mostaganem", [
        "Mostaganem", "Sayada", "Fornaka", "Stidia", "Ain Nouissy",
        "Hassi Maameche", "Ain Tadles", "Sour", "Oued El Kheir",
        "Sidi Bellater", "Kheiredine", "Sidi Ali", "Abdelmalek Ramdane",
        "Hadjadj", "Nekmaria", "Sidi Lakhdar", "Achaacha", "Khadra",
        "Bouguirat", "Sirat", "Ain Sidi Cherif", "Mesra", "Mansourah",
        "Souaflia", "Ouled Boughalem", "Ouled Maallah", "Mezghrane",
        "Ain Boudinar", "Tazgait", "Safsaf", "Touahria", "El Hassaine",
        "Benabdelmalek Ramdane",
    ]),
    ("28", "M'Sila", [
        "M'Sila", "Maadid", "Hammam Dhalaa", "Ouled Derradj", "Tarmount",
        "Mtarfa", "Khoubana", "M'Cif", "Chellal", "Ouled Madhi",
        "Magra", "Berhoum", "Ain Khadra", "Ouled Addi Guebala", "Belaiba",
        "Sidi Aissa", "Ain El Hadjel", "Sidi Hadjeres", "Ouanougha",
        "Bou Saada", "Ouled Sidi Brahim", "Sidi Ameur", "Tamsa",
        "Ben Srour", "Ouled Slimane", "El Houamed", "El Hamel",
        "Ouled Mansour", "Maarif", "Dehahna", "Bouti Sayah", "Khettouti Sed El Djir",
        "Zarzour", "Oued Chair", "Benzouh", "Bir Foda", "Ain Fares",
        "Sidi M'Hamed", "Ouled Atia", "Souamaa", "Ain El Melh",
        "Medjedel", "Slim", "Ain Errich", "Beni Ilmane", "Oultene",
        "Djebel Messaad", "Mohammed Boudiaf", "El Khoubana",
    ]),
    ("29", "Mascara", [
        "Mascara", "Bou Hanifia", "Tizi", "Hacine", "Maoussa", "Teghennif",
        "El Hachem", "Sidi Kada", "Zelmata", "Oued El Abtal", "Ain Fares",
        "Ain Fekan", "Khalouia", "El Menaouer", "Oued Taria", "Aouf",
        "Ain Ferah", "Ghriss", "Froha", "Matemore", "Makdha", "Sidi Boussaid",
        "El Bordj", "Ras El Ain Amirouche", "Gharrous", "Guerdjoum",
        "Chorfa", "Ras Ain Amirouche", "Nesmoth", "El Ghomri", "Sedjerara",
        "Moctadouz", "Bou Henni", "Guettena", "El Mamounia", "El Keurt",
        "Mohammadia", "Sig", "Oggaz", "Alaimia", "El Gaada", "Zahana",
        "Tighennif", "Bou Henni", "Sehailia", "Ferraguig", "Ain Frass",
    ]),
    ("30", "Ouargla", [
        "Ouargla", "Ain Beida", "N'Goussa", "Hassi Ben Abdellah",
        "Rouissat", "Balidat Ameur", "Tebesbest", "Nezla", "Zaouia El Abidia",
        "Sidi Slimane", "Sidi Khouiled", "Hassi Messaoud", "Bordj Omar Driss",
        "Taibet", "Benaceur", "M'Naguer", "El Hadjira", "El Alia",
        "El Borma", "Megarine",
    ]),
    ("31", "Oran", [
        "Oran", "Gdyel", "Bir El Djir", "Hassi Bounif", "Es Senia",
        "Arzew", "Bethioua", "Marsat El Hadjadj", "Ain Turk", "El Ancar",
        "Oued Tlelat", "Tafraoui", "Sidi Chami", "Boufatis", "Mers El Kebir",
        "Bousfer", "El Karma", "El Braya", "Hassi Ben Okba", "Ben Freha",
        "Hassi Mefsoukh", "Sidi Ben Yebka", "Messerghin", "Boutlelis",
        "Ain Kerma", "Ain Biya",
    ]),
    ("32", "El Bayadh", [
        "El Bayadh", "Rogassa", "Stitten", "Brezina", "Ghassoul",
        "Boualem", "El Abiodh Sidi Cheikh", "Ain El Orak", "Arbaouat",
        "Bougtoub", "El Kheiter", "Kef El Ahmar", "Boussemghoun",
        "Chellala", "Krakda", "El Bnoud", "Cheguig", "Sidi Ameur",
        "El Mehara", "Tousmouline", "Sidi Slimane", "Sidi Tifour",
    ]),
    ("33", "Illizi", [
        "Illizi", "Djanet", "Debdeb", "Bordj Omar Driss", "In Amenas",
        "Bordj El Haouas",
    ]),
    ("34", "Bordj Bou Arréridj", [
        "Bordj Bou Arréridj", "Ras El Oued", "Bordj Zemoura", "Mansoura",
        "El Mhir", "Ben Daoud", "El Achir", "Ain Taghrout", "Bordj Ghdir",
        "Sidi Embarek", "El Hamadia", "Belimour", "Ghailasa", "El Ach",
        "El Anseur", "Tafreg", "Colla", "Tixter", "El Main", "Djaafra",
        "El Euch", "Ksour", "Ouled Brahem", "Hasnaoua", "Khelil",
        "Taglait", "Ain Tesra", "Bir Kasdali", "Ouled Sidi Brahim",
        "Tefreg", "Haraza", "Rabta", "Medjana", "Teniet En Nasr",
    ]),
    ("35", "Boumerdès", [
        "Boumerdès", "Boudouaou", "Afir", "Bordj Menaiel", "Baghlia",
        "Sidi Daoud", "Naciria", "Djinet", "Isser", "Zemmouri",
        "Si Mustapha", "Tidjelabine", "Chabet El Ameur", "Thenia",
        "Timezrit", "Corso", "Ouled Moussa", "Larbatache", "Bouzegza Keddara",
        "Taourga", "Ouled Aissa", "Ben Choud", "Dellys", "Ammal",
        "Beni Amrane", "Souk El Had", "Boudouaou El Bahri", "Ouled Hedadj",
        "Laghata", "Hammedi", "Khemis El Khechna", "El Kharrouba",
        "Kaddara", "Ouled Heddadj", "Leghata",
    ]),
    ("36", "El Tarf", [
        "El Tarf", "Bouhadjar", "Ben M'Hidi", "Bougous", "El Kala",
        "Ain El Assel", "El Aioun", "Bouteldja", "Souarekh", "Berrihane",
        "Lac Des Oiseaux", "Chefia", "Drean", "Chihani", "Chebaita Mokhtar",
        "Besbes", "Asfour", "Echatt", "Zerizer", "Zitouna", "Ain Kerma",
        "Oued Zitoun", "Hammam Beni Salah", "Raml Souk",
    ]),
    ("37", "Tindouf", [
        "Tindouf", "Oum El Assel",
    ]),
    ("38", "Tissemsilt", [
        "Tissemsilt", "Bordj Bou Naama", "Theniet El Had", "Lazharia",
        "Beni Chaib", "Lardjem", "Melaab", "Sidi Lantri", "Bordj El Emir Abdelkader",
        "Layoune", "Khemisti", "Ouled Bessem", "Ammari", "Youssoufia",
        "Sidi Boutouchent", "Larbaa", "Maasem", "Sidi Abed", "Tamalaht",
        "Sidi Slimane", "Boucaid", "Beni Lahcene",
    ]),
    ("39", "El Oued", [
        "El Oued", "Robbah", "Oued El Alenda", "Bayadha", "Nakhla",
        "Guemar", "Kouinine", "Reguiba", "Hamraia", "Taghzout",
        "Debila", "Hassani Abdelkrim", "Hassi Khalifa", "Taleb Larbi",
        "Douar El Ma", "Sidi Aoun", "Trifaoui", "Magrane", "Ben Guecha",
        "Ourmes", "El Ogla", "Mih Ouansa", "El Mghair", "Djamaa",
        "Sidi Amrane", "Still", "M'Rara", "Sidi Khelil", "Tendla",
        "Oum Touyour", "Nakhla",
    ]),
    ("40", "Khenchela", [
        "Khenchela", "Mtoussa", "Kais", "Baghai", "El Hamma", "Ain Touila",
        "Taouzianat", "Bouhmama", "El Oueldja", "Remila", "Cherchar",
        "Djellal", "Babar", "Tamza", "Ensigha", "Ouled Rechache",
        "El Mahmal", "Msara", "Yabous", "Khirane", "Chelia",
    ]),
    ("41", "Souk Ahras", [
        "Souk Ahras", "Sedrata", "Hanancha", "Mechroha", "Ouled Driss",
        "Tiffech", "Zaarouria", "Taoura", "Drea", "Haddada", "Khedara",
        "Merahna", "Ouled Moumen", "Bir Bouhouche", "M'Daourouche",
        "Oum El Adhaim", "Ain Zana", "Ain Soltane", "Ouillen", "Sidi Fredj",
        "Safel El Ouiden", "Ragouba", "Khemissa", "Oued Keberit",
        "Terraguelt", "Zouabi",
    ]),
    ("42", "Tipaza", [
        "Tipaza", "Menaceur", "Larhat", "Douaouda", "Bourkika",
        "Khemisti", "Aghbal", "Hadjout", "Sidi Amar", "Gouraya",
        "Nodor", "Chaiba", "Ain Tagourait", "Cherchell", "Damous",
        "Meurad", "Fouka", "Bou Ismail", "Ahmer El Ain", "Bou Haroun",
        "Sidi Ghiles", "Messelmoun", "Sidi Rached", "Kolea", "Attatba",
        "Sidi Semiane", "Beni Milleuk", "Hadjret Ennous",
    ]),
    ("43", "Mila", [
        "Mila", "Ferdjioua", "Chelghoum Laid", "Oued Athmenia", "Ain Mellouk",
        "Telerghma", "Oued Seguen", "Tadjenanet", "Benyahia Abderrahmane",
        "Oued Endja", "Ahmed Rachedi", "Ouled Khalouf", "Tiberguent",
        "Bouhatem", "Rouached", "Tessala Lemtai", "Grarem Gouga",
        "Sidi Merouane", "Tassadane Haddada", "Derrahi Bousselah",
        "Minar Zarza", "Amira Arres", "Terrai Bainen", "Hamala",
        "Ain Tine", "El Mechira", "Sidi Khelifa", "Zeghaia", "Elayadi Barbes",
        "Ain Beida Harriche", "Yahia Beniguecha", "Chigara", "El Ghar Bou Chari",
    ]),
    ("44", "Aïn Defla", [
        "Aïn Defla", "Miliana", "Boumedfaa", "Khemis Miliana", "Hammam Righa",
        "Arib", "Djelida", "El Amra", "Bourached", "El Attaf",
        "El Abadia", "Djendel", "Oued Chorfa", "Ain Lechiakh", "Oued Djemaa",
        "Rouina", "Zeddine", "El Hassania", "Bir Ould Khelifa", "Ain Soltane",
        "Tarik Ibn Ziad", "Bordj Emir Khaled", "Ain Torki", "Sidi Lakhdar",
        "Ben Allal", "Ain Benian", "Hoceinia", "Barbouche", "Djemaa Ouled Cheikh",
        "Mekhatria", "Bathia", "Tacheta Zougagha", "Ain Bouyahia",
        "El Maine", "Tiberkanine", "Belaas",
    ]),
    ("45", "Naâma", [
        "Naâma", "Mecheria", "Ain Sefra", "Tiout", "Sfissifa", "Moghrar",
        "Assela", "Djeniane Bourzeg", "Ain Ben Khelil", "Makman Ben Amer",
        "Kasdir", "El Biod",
    ]),
    ("46", "Aïn Témouchent", [
        "Aïn Témouchent", "Chaabet El Ham", "Ain Kihal", "Hammam Bou Hadjar",
        "Bou Zedjar", "Oued Berkeche", "Aghlal", "Terga", "Ain Tolba",
        "El Malah", "Sidi Ben Adda", "Aoubellil", "El Amria", "Hassi El Ghella",
        "Hassasna", "Ouled Boudjemaa", "Ain Arbaa", "Tamzoura",
        "Chentouf", "Sidi Safi", "Oulhaca El Gheraba", "Tadmaya",
        "El Emir Abdelkader", "Ain El Arbaa", "Beni Saf", "Sidi Boumediene",
        "Oued Sabah", "Ouled Kihal",
    ]),
    ("47", "Ghardaïa", [
        "Ghardaïa", "El Meniaa", "Dhayet Bendhahoua", "Berriane", "Metlili",
        "El Guerrara", "El Atteuf", "Zelfana", "Sebseb", "Bounoura",
        "Hassi Fehal", "Hassi Gara", "Mansoura",
    ]),
    ("48", "Relizane", [
        "Relizane", "Oued Rhiou", "Belaassel Bouzegza", "Sidi Saada",
        "Ouled Aiche", "Sidi Lazreg", "El Hamadna", "Sidi M'Hamed Ben Ali",
        "Mediouna", "Sidi Khettab", "Ammi Moussa", "Zemmoura", "Beni Dergoun",
        "Djidiouia", "El Guettar", "Hamri", "El Matmar", "Sidi M'Hamed Ben Aouda",
        "Ain Tarek", "Oued El Djemaa", "Ramka", "Mendes", "Lahlef",
        "Beni Zentis", "Souk El Had", "Dar Ben Abdelah", "El Hassi",
        "Had Echkalla", "Bendaoud", "El Ouldja", "Mazouna", "Kalaa",
        "Ain Rahma", "Yellel", "Oued Essalem", "Ouarizane", "Merdja Sidi Abed",
        "Ouled Sidi Mihoub",
    ]),
    ("49", "Timimoun", [
        "Timimoun", "Ouled Said", "Aougrout", "Deldoul", "Charouine",
        "Metarfa", "Talmine", "Ouled Aissa", "Tinerkouk", "Ksar Kaddour",
    ]),
    ("50", "Bordj Badji Mokhtar", [
        "Bordj Badji Mokhtar", "Timiaouine",
    ]),
    ("51", "Ouled Djellal", [
        "Ouled Djellal", "Sidi Khaled", "Doucen", "Ras El Miaad",
        "Besbes", "Ech Chaiba",
    ]),
    ("52", "Béni Abbès", [
        "Béni Abbès", "Igli", "El Ouata", "Kerzaz", "Timoudi",
        "Ouled Khodeir", "Beni Ikhlef", "Tabelbala", "Ksabi", "Tamtert",
    ]),
    ("53", "In Salah", [
        "In Salah", "In Ghar", "Foggaret Ezzoua",
    ]),
    ("54", "In Guezzam", [
        "In Guezzam", "Tin Zaouatine",
    ]),
    ("55", "Touggourt", [
        "Touggourt", "Nezla", "Tebesbest", "Zaouia El Abidia", "Temacine",
        "Blidet Amor", "Megarine", "El Hadjira", "El Alia", "Sidi Slimane",
        "Taibet", "Benaceur", "M'Naguer",
    ]),
    ("56", "Djanet", [
        "Djanet", "Bordj El Haouas",
    ]),
    ("57", "El M'Ghair", [
        "El M'Ghair", "Djamaa", "Sidi Amrane", "Still", "Tenedla",
        "M'Rara", "Oum Touyour", "Sidi Khelil",
    ]),
    ("58", "El Meniaa", [
        "El Meniaa", "Hassi Gara", "Hassi Fehal",
    ]),
]


# ─── API dérivée (ne pas modifier les noms) ──────────────────────────────────
WILAYAS: list[str] = [nom for _code, nom, _communes in _ALGERIA]

WILAYA_CODES: dict[str, str] = {nom: code for code, nom, _communes in _ALGERIA}

COMMUNES_BY_WILAYA: dict[str, list[str]] = {
    nom: sorted(set(communes)) for _code, nom, communes in _ALGERIA
}


if __name__ == "__main__":
    # Bloc de cohérence : vérifie la structure et affiche quelques compteurs.
    assert len(WILAYAS) == 58, f"Attendu 58 wilayas, obtenu {len(WILAYAS)}"
    assert set(WILAYA_CODES) == set(WILAYAS), "Clés WILAYA_CODES != WILAYAS"
    assert set(COMMUNES_BY_WILAYA) == set(WILAYAS), "Clés COMMUNES_BY_WILAYA != WILAYAS"
    total = sum(len(c) for c in COMMUNES_BY_WILAYA.values())
    vides = [w for w, c in COMMUNES_BY_WILAYA.items() if not c]
    print(f"Wilayas : {len(WILAYAS)}")
    print(f"Communes (total) : {total}")
    print(f"Wilayas sans commune : {vides or 'aucune'}")
